version: 2
updates:
  # Frontend NPM dependencies configuration
  - package-ecosystem: "npm"
    directory: "/src/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    versioning-strategy: "auto"
    allow:
      - "patch"
      - "minor"
    assignees:
      - "@team/frontend"
    reviewers:
      - "@team/frontend-leads"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    groups:
      next-js:
        patterns:
          - "next"
          - "@types/next"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      testing:
        patterns:
          - "jest"
          - "@testing-library/*"

  # Backend Python dependencies configuration
  - package-ecosystem: "pip"
    directory: "/src/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    versioning-strategy: "auto"
    allow:
      - "patch"
      - "minor"
    assignees:
      - "@team/backend"
    reviewers:
      - "@team/backend-leads"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    groups:
      django:
        patterns:
          - "django"
          - "djangorestframework"
      testing:
        patterns:
          - "pytest*"
          - "factory-boy"
          - "faker"

  # Docker dependencies configuration
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    assignees:
      - "@team/devops"
    reviewers:
      - "@team/devops-leads"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"